version: '2'
services:
  interfaceserver:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 channels_simple.asgi:channel_layer
    user: app
    working_dir: /app
    ports:
      - 8000:8000
    volumes:
      - .:/app
  workerserver:
    build: .
    user: app
    working_dir: /app
    command: python manage.py runworker --settings=channels_simple.settings_docker_compose
    volumes:
      - .:/app
  database:
    image: postgres:9.5
  redis:
    image: redis:3.0-alpine
  nginx:
#    dns:
#      - 127.0.0.1
#      - 8.8.8.8
    image: nginx
    depends_on:
      - database
      - interfaceserver
      - redis
      - workerserver
    volumes:
      - .:/app
      - ./devscripts/docker-compose/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8668:80