uwsgi:
  chdir: /code
  enable-threads: true
  logfile-chmod: 644
  logto: /code/logs/uwsgi.log
  master: true
  pidfile: /code/logs/uwsgi.pid
  pythonpath: .
  uwsgi-socket: 0.0.0.0:7000
  vacuum: true
  workers: 4
  wsgi-file: channels_simple/wsgi.py

