# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 03:20
from __future__ import unicode_literals

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    IntegerValue = apps.get_model("channels_simple_app", "IntegerValue")
    IntegerValue.objects.create(pk=1, name='int1', value=0)


def reverse_func(apps, schema_editor):
    IntegerValue = apps.get_model("channels_simple_app", "IntegerValue")
    IntegerValue.objects.get(pk=1).delete()


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('room', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'chat messages',
                'ordering': ['message'],
            },
        ),
        migrations.CreateModel(
            name='IntegerValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('value', models.IntegerField(default=0)),
            ],
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
