# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels_simple_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegerValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('value', models.IntegerField(default=0)),
            ],
        ),
    ]
